version: 1.0.{build}

skip_tags: true
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: '\mig-media-v4lcamera\MIG-V4LCamera\Output\MIG-V4LCamera.zip'

deploy:
  release: V$(appveyor_build_version)
  description: 'MIG-V4LCamera Version $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: 6xpJrNRZ7YlU22YNrDRs9dAmvp2LIJ4O7t+a5443/NERIk9Aspip7glMn9O4sqU6
  draft: false
  prerelease: true
  on:
    branch: master                  # release from master branch only
#    appveyor_repo_tag: false        # deploy on tag push only