version: 1.0.{build}

skip_tags: true
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: '\*.zip'

deploy:
  release: V$(appveyor_build_version)
  description: 'mig-interface-skelton Version $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: nNJ0tuvMX88/5GPQFV4mtqQe3pRgsJlOd8pvbi0+WeCOsyeNY3L///lRC8pF29wo6J+5b6TPLDDKdKGXveZo9FICP+6k95LkQCvlFzaXb4I=
  draft: false
  prerelease: true
  on:
    branch: master                  # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only